arrowParens: 'avoid'
printWidth: 120
quoteProps: 'as-needed'
semi: true
singleQuote: true
tabWidth: 4
trailingComma: 'all'
jsxSingleQuote: true
overrides:
  - files: '*.scss'
    options:
      tabWidth: 2
  - files: '*.yaml'
    options:
      tabWidth: 2
  - files: '*.yml'
    options:
      tabWidth: 2
  - files: '*.json'
    options:
      tabWidth: 2
  - files: '*.graphql'
    options:
      tabWidth: 2
  - files: '*.md'
    options:
      tabWidth: 2
